export const VIEW_DETAILS = 'VIEW_DETAILS';
export const SAVE_MOVIE = 'SAVE_MOVIE';
export const DELETE_MOVIE = 'DELETE_MOVIE';
export const FILTER_MOVIES_BY_QUERY = 'FILTER_MOVIES_BY_QUERY';
export const FILTER_MOVIES_BY_GENRE = 'FILTER_MOVIES_BY_GENRE';
export const SORT_MOVIES = 'SORT_MOVIES';
